name: Pixelpickle
favicon: null
layout_spectrum: 0.50451
typography_spectrum: 0.5920484075322747
title: Pixelpickle Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-4692760-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b6d437'
    - '#a8a8a8'
    - '#474746'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
