name: Pixelpickle
favicon: null
layout_spectrum: 0.4405987970530987
typography_spectrum: 0.1404381711035967
title: Pixelpickle Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13877753796987236
  lightness: 0.6632798830978572
  saturation: 0.9539183136075735
  rhythmicContrast: 0.8580766876693815
purpose: []
