name: Pixelpickle
favicon: null
layout_spectrum: 0.88989
typography_spectrum: 0.14795
title: Pixelpickle Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b6d437'
    - '#a8a8a8'
    - '#474746'
  brandStrength: 0.13877753796987236
  lightness: 0.6632798830978572
  saturation: 0.9539183136075735
  rhythmicContrast: 0.8580766876693815
purpose: []
