layout_spectrum: 0.052943561458960176
typography_spectrum: 0.5491064132656902
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b6d437'
    - '#a8a8a8'
    - '#474746'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-4692760-1
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cfe4ef05-0168-4722-9cc8-ea9a1945a6cf.png
name: Pixelpickle
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Pixelpickle Games
purpose: []
